version: '3'

services:
  frontend:
    restart: always
    container_name: frontend
    build:
      context: .
      args:
        - NEXT_PUBLIC_API=${NEXT_PUBLIC_API}
        - NEXT_PUBLIC_SLACK_URL=${NEXT_PUBLIC_SLACK_URL}
        - NEXT_PUBLIC_BRAND=${NEXT_PUBLIC_BRAND}
        - NEXT_PUBLIC_FRONTEND_URL=${FRONTEND_URL}
        - REVALIDATE_SECRET=${REVALIDATE_SECRET}
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API: ${NEXT_PUBLIC_API}
      NEXT_PUBLIC_SLACK_URL: ${NEXT_PUBLIC_SLACK_URL}
      NEXT_PUBLIC_BRAND: ${NEXT_PUBLIC_BRAND}
      NEXT_PUBLIC_FRONTACCOUNT_URL: ${FRONTEND_URL}
      REVALIDATE_SECRET: ${REVALIDATE_SECRET}
    depends_on:
      - database
      - nestjs
    networks:
      - marweb
networks:
  marweb:
    driver: bridge
